<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>ScreenAutomationTool</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Tesseract" Version="5.2.0" />
		<PackageReference Include="OpenCvSharp4" Version="4.13.0.20260226" />
		<PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260226" />
	</ItemGroup>

	<ItemGroup>
		<None Update="tessdata\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>